# create your drupal and postgres config here, based off the last assignment
version: '2'

networks: 
    drupal-network:        

services:
    drupal:
        image: custom-drupal
        build: .
        networks:
            - drupal-network
        ports:
            - '8080:80'
        volumes: 
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles       
            - drupal-sites:/var/www/html/sites      
            - drupal-themes:/var/www/html/themes
            - drupal-data:/var/lib/postgresql/data
        depends_on:
            - postgres

    postgres:
        image: postgres:9.6
        networks: 
            - drupal-network
        environment:
            - POSTGRES_PASSWORD=pass

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    drupal-data: